target remote : 3333
monitor gdb_breakpoint_override hard

define dispi
    display/i $pc
end
document dispi
    Display the current instruction
    Usage: dispi
end

define resync
    # Resynchronize GDB with the GDB server
    monitor halt
    monitor gdb_sync
    monitor cortex_a maskisr on

    cont
end
document resync
    Resynchronize GDB with the GDB server
    Usage: resync
end

alias -a reg = info registers

dispi

resync
